baseURL = 'https://thekamboy.github.io/'
languageCode = 'en-us'
title = "KamboyDev's Cool Website"
theme = 'kaslaanka'

[params]
sitename = "KamboyDev's Cool Website"
copyrights = "Kameron Clouser"
defaultList = "global"
paginationLen = 3
projectsURL = "https://github.com/TheKamboy"
brief_about = "<center>Kaslaanka theme demo made with ❤️️</center>"

[[menu.primary]]
name = "Home"
url = "/"
weight = 1

[[menu.primary]]
name = "About"
url = "/about"
weight = 2

[[menu.primary]]
name = "Subscribe"
url = "https://www.youtube.com/channel/UCtW2DfcLBqNRX5Ih3LF8GHw"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'
