#!/bin/bash

shouldquit=false

fileeditor=nvim

locationofpostman=$(pwd)

newpostarg=false

makenewpost() {
  filename=$(gum input --header="What will the file name be for the post?")

  if [ -n "$filename" ]; then
    hugo new content content/blog/en/$filename.md

    if [ "$newpostarg" = false ]; then
      $fileeditor content/blog/en/$filename.md
    fi
  fi
}

openpost() {
  cd content/blog/en
  file=$(gum file)

  if [ -n "$file" ]; then
    $fileeditor $file
  fi

  cd $locationofpostman
}

mainMenu() {
  echo ""
  menu=$(gum choose --header="Postman" "Exit" "Create Post" "Open Post" "Preview Website" "Open Website File" "Open Lazygit")

  if [ "$menu" = "Exit" ]; then
    shouldquit=true
  elif [ "$menu" = "Create Post" ]; then
    makenewpost
  elif [ "$menu" = "Open Post" ]; then
    openpost
  elif [ "$menu" = "Preview Website" ]; then
    hugo server -D
    echo ""
  elif [ "$menu" = "Open Website File" ]; then
    file=$(gum file)

    if [ -n "$file" ]; then
      $fileeditor $file
    fi
  elif [ "$menu" = "Open Lazygit" ]; then
    lazygit
  fi
}

idk=false

while getopts n: flag
do
    case "${flag}" in
        n) newpostarg=${OPTARG};;
    esac
done

if [ "$newpostarg" = true ]; then
  makenewpost
  exit
fi

while [ "$shouldquit" = false ]; do
  mainMenu
done
