#!/bin/bash

shouldquit=false

fileeditor=nvim

locationofpostman=$(pwd)

makenewpost() {
  filename=$(gum input --header="What will the file name be for the post?")

  hugo new content content/blog/en/$filename.md

  $fileeditor content/blog/en/$filename.md
}

openpost() {
  cd content/blog/en
  file=$(gum file)

  if [ -n "$file" ]; then
    $fileeditor $file
  fi

  cd $locationofpostman
}

mainMenu() {
  echo ""
  menu=$(gum choose --header="Postman" "Exit" "Create Post" "Open Post" "Preview Website" "Open Website File" "Open Lazygit")

  if [ "$menu" = "Exit" ]; then
    shouldquit=true
  elif [ "$menu" = "Create Post" ]; then
    makenewpost
  elif [ "$menu" = "Open Post" ]; then
    openpost
  elif [ "$menu" = "Preview Website" ]; then
    hugo server -D
    echo ""
  elif [ "$menu" = "Open Website File" ]; then
    file=$(gum file)

    if [ -n "$file" ]; then
      $fileeditor $file
    fi
  elif [ "$menu" = "Open Lazygit" ]; then
    lazygit
  fi
}

while [ "$shouldquit" = false ]; do
  mainMenu
done
